//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLC_Design
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YCGInventoryEntities : DbContext
    {
        public YCGInventoryEntities()
            : base("name=YCGInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_ReqFormIt_Id(string reqNo)
        {
            var reqNoParameter = reqNo != null ?
                new ObjectParameter("ReqNo", reqNo) :
                new ObjectParameter("ReqNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ReqFormIt_Id", reqNoParameter);
        }
    }
}
